### ISSUE TITLE
Discussion on Language / Localization

### ISSUE THREAD

**Issue by soruly** [soruly/awesome-acg#13]
In this list, some projects are in Japanese / Chinese only. And some projects are targeted only on English / Chinese ACG community. I haven't decide how to take care of this issue yet, so I'm asking for opinions. We could:
- separate the list into Chinese, English, Japanese list (not preferred)
- add a language tag in front of description (if applicable)
- just leave it be, let the existing description describes that the project is targeted for specific languages / websites

**Comment by zcyzcy88** [comment]
I choose _just leave it be_:
- The Machine Translation is good enough.
- The important thing of many resources is not language.

**Comment by ppzvpp** [comment]
- _add a language tag in front of description_ (tags for both the project and its target)
- _just leave it be, let the existing description describes that the project is targeted for specific languages / websites_  (if some of projects are in dual or multi languages, we can describe in those languages at the same time, I prefer this solution)
