### ISSUE TITLE
Shameless self promoting

### ISSUE THREAD

**Issue by spillerrec** [soruly/awesome-acg#3]
Some stuff I have made, add it if you find it interesting
### cgCompress

Compresses visual novel graphics by finding the optimal sequence of differences to recreate the original images. Drastically reduces file size compared to PNG (like 90-95% for some VNs) and about 20 % to 7z compressed BMP files. More info: http://spillerrec.dk/2014/02/compressing-vn-cgs/
https://github.com/spillerrec/cgCompress
### Overmix

Stitching of anime screenshots, but tries to remove compression artifacts by combining as many images as possible. A bit on the experimental side.
- Removing mosaic censorship: http://spillerrec.dk/2015/07/removing-mosaic-censor/
- Animated stitched (still far from perfect): http://spillerrec.dk/2014/11/animated-stitches/
- Logo/credits detection and removal: http://spillerrec.dk/2013/12/logo-detection-and-removal/

https://github.com/spillerrec/Overmix
I have big plans for even more sophisticated stuff (involving "waifu2x" and multi-frame super resolution methods), but that will not be for a while...
### BooruSurfer

A web-based interface for several Booru's such as danbooru, konachan, yandere-chan, gelbooru, sankaku, other boorus with RSS-feeds, etc.
Currently porting it to C++ from PHP:
BooruSurfer (PHP, danbooru and sankaku broken/outdated due changes in API): https://github.com/spillerrec/BooruSurfer
BooruSurfer2 (C++, danbooru broken, gelbooru, and RSS-feed-based not added yet): https://github.com/spillerrec/BooruSurfer2

**Comment by soruly** [comment]
This is truely awesome! Thanks @spillerrec for creating a better world :D
