### ISSUE TITLE
Add gallery-dl and others

### ISSUE THREAD

**Issue by DonaldTsang** [soruly/awesome-acg#43]
https://github.com/mikf/gallery-dl and https://github.com/Bionus/imgbrd-grabber and https://github.com/Xonshiz/comic-dl are the best downloaders in the field

**Comment by DonaldTsang** [comment]
Pixiv
https://github.com/vicety/Pixiv-Crawler
https://github.com/imn5100/pixivDownloader
https://github.com/xingoxu/pixivDownloader-WPF
https://github.com/LewisTian/Crawler
https://github.com/Akaisorani/pixiv-crawler

Manga
https://github.com/abcfy2/getComic
https://github.com/NguyenDanPhuong/MangaRipper
https://github.com/wellwind/8ComicDownloaderElectron
https://github.com/Xonshiz/ReadComicOnline-Downloader
https://github.com/nuncjo/comicthief
https://github.com/Girbons/comics-scraper

**Comment by soruly** [comment]
I've added some popular ones and I'm leaving less popular projects here.
If there're some projects that you think worth adding to the list (regardless of popularity), please open a new issue.

**Comment by DonaldTsang** [comment]
Sounds good
