### ISSUE TITLE
Add other imageboards

### ISSUE THREAD

**Issue by DonaldTsang** [soruly/awesome-acg#45]
- [ ] https://github.com/zixaphir/gelbooru-fork
- [ ] https://code.shishnet.org/shimmie2/
- [ ] https://code.acr.moe/kazari/myimouto-untouched

**Comment by soruly** [comment]
Not adding these because:
gelbooru-fork ==> lack of project descriptions
shimmie2 ==> not quite related to ACG
myimouto-untouched ==> appears to be no longer maintained (and too many mirrors and forks)
